### ISSUE TITLE
It doesn't appear

### ISSUE THREAD

**Issue by juandiegoapps** [BCGDV-ASIA/android-widget-fanmenu#4]
Hi. I'm implementing this widget following your guide, but when I launch the emulator, and the app runs on it, the widget doesn't appear. I don't know why, I don't even have errors... At the XML file, android:visibility="gone" is set, and not invisible...

**Comment by alphamu** [comment]
If you want it visible by default, don't get visibility to GONE.
It was probably an oversight that visibility="gone" was left in the example.
Are you trying to make the fan menu visible by default, or do you want it to show up when some action is taken?

**Comment by adipatijukir** [comment]
how to make it go to another activity?
