### ISSUE TITLE
I want use custom font for buttons

### ISSUE THREAD

**Issue by esmailshahbazi** [BCGDV-ASIA/android-widget-fanmenu#8]
Help me to use custom font for button

**Comment by alphamu** [comment]
If you are using Calligraphy, you can set the custom font on the view in the XML and it should work, the widget extends TextView and uses the text views paint object to draw the text.

**Comment by alphamu** [comment]
Just checked, the implementation is wrong, so this wouldn't work, I'll apply a fix and get back to you.

**Comment by alphamu** [comment]
Version 1.4 fixes this issue. I've test it with Calligraphy as well as the new android XML fonts
